base_url = "https://blog.danieliu.xyz"
title = "pinosaur's blog"
description = "random blurbs about software and japanese"
default_language = "en"

compile_sass = false
build_search_index = true

generate_feed = true
feed_filename = "atom.xml"

[markdown]
highlight_code = true
highlight_theme = "monokai"
render_emoji = true

[search]
include_title = true
include_description = false
include_content = true
truncate_content_length = 100

[extra]
