on:
  push:
    branches:
      - master
  workflow_dispatch: {}

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/mrpicklepinosaur/blog:latest
            ghcr.io/mrpicklepinosaur/blog:${{ github.sha }}
  deploy:
    name: Deploy
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Set the Kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: ${{ secrets.KUBERNETES_SERVER_URL }}
          k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

      - name: Checkout source code
        uses: actions/checkout@v3

#       - name: Deploy to the Kubernetes cluster
#         uses: azure/k8s-deploy@v1
#         with:
#           namespace: default
#           manifests: |
#             kubernetes/deployment.yaml
#             kubernetes/ingress.yaml
#             kubernetes/service.yaml
#           images: |
#             ghcr.io/MrPicklePinosaur/blog:${{ github.sha }}

